services:
  justbin:
    build: .
    ports:
      - "8080:8080"
    env_file: .sample.env
    networks:
      - default
  db:
    image: postgres
    shm_size: 128mb
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .sample.env

  s3:
    image: minio/minio
    command: minio server /data
    networks:
      - default
    env_file: .sample.env
    volumes:
      - ./data/s3:/data

networks:
  default:
