services:
  justbin:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - default
  db:
    image: postgres
    shm_size: 128mb
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345678

networks:
  default:
